method: grid
name: triplet_encoder
parameters:
  backbone:
    value: densenet161
  dim_embeddings:
    values:
      - 128
      - 256
  epochs:
    value: 50
  batch_size:
    values:
      - 16
      - 32
  learning_rate:
    values:
      - 0.001
      - 0.0001
  weight_decay:
    values:
      - 0.001
      - 0.0001
  scheduler:
    value: true
  scheduler_gamma:
    values: 
      - 0.9
      - 0.6
      - 0.3
  scheduler_stepsize:
    values:
      - 7
      - 15
program: scripts/train-triplet_encoder.py
project: siamese-approach