method: grid
name: vit_b_16
parameters:
  backbone:
    value: vit_b_16
  batch_size:
    values:
      - 16
      - 32
  epochs:
    value: 30
  learning_rate:
    values:
      - 0.001
      - 0.0001
  scheduler:
    value: true
  scheduler_gamma:
    values: 
      - 0.9
      - 0.6
      - 0.3
  scheduler_stepsize:
    values:
      - 10
      - 15
  weight_decay:
    values:
      - 0.001
      - 0.0001
program: scripts/training-complete-model.py
project: overfitting-approach