method: grid
name: base_models
parameters:
  backbone:
    values: 
      - densenet201
      - resnet18
      - resnet34
      - resnet50
      - resnet101
      - resnet152
      - resnext101
      - efficientnet_b0
      - efficientnet_b4
      - vit_b_16
      - vit_b_32
  main_class:
    values: 
      - dm_generated
      - gan_generated
      - real
  epochs:
    value: 30
  batch_size:
    values:
      - 16
      - 32
  learning_rate:
    values:
      - 0.001
      - 0.0001
  weight_decay:
    values:
      - 0.001
      - 0.0001
  scheduler:
    value: true
  scheduler_gamma:
    values: 
      - 0.9
      - 0.6
      - 0.3
  scheduler_stepsize:
    values:
      - 7
      - 15
program: scripts/training/train-base_model.py
project: siamese-approach