method: grid
name: complete_models
parameters:
  backbone:
    values: 
      - densenet121
      - densenet161
  epochs:
    value: 100
  batch_size:
    values:
      - 16
      - 32
  learning_rate:
    values:
      - 0.001
      - 0.0001
  weight_decay:
    values:
      - 0.001
      - 0.0001
  scheduler:
    value: true
  scheduler_gamma:
    values: 
      - 0.9
      - 0.6
      - 0.3
  scheduler_stepsize:
    values:
      - 7
      - 15
program: scripts/training/train-complete_model.py
project: siamese-approach